// import { css } from '@emotion/react';
import Head from 'next/head';

// import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Ahoj</h1>
        <a>asdfasdf</a>
        <p>sdafasdfasdfasdfasdf</p>
      </main>
    </div>
  );
}
